FROM python:3.11-slim

# WORKDIR /app

# # Install dependencies
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

# # Copy ingestion code
# COPY ingestion/ /app/ingestion/
# COPY config/ /app/config/

# # Set Python path
# ENV PYTHONPATH=/app

# CMD ["python", "-m", "ingestion.chains.eth_mainnet.block_scanner"]
